version: '3.7'
services: 
    elasticsearch:
        image: elasticsearch:7.6.2
        container_name: elasticsearch
        ports: 
            # The host running Docker (localhost) hast to send metrics to this port.
            - 9200:9200
            # Unknown
            #- 9300:9300
        networks: 
            - elk_net
        volumes:
            # Volume for logs persistence
            # If you want to persist the logs in your local filesystem 
            #use bind type and uncomment source
            - type: tmpfs
              #source: ./logs
              target: /usr/share/elasticsearch/data
        environment: 
            - discovery.type=single-node
    logstash:
        image: docker.elastic.co/logstash/logstash:7.6.2
        container_name: logstash
        #ports:
            # Unknown
            #- 5000:5000
            # Gets basic data about logstash node
            #- 9600:9600
            # Apps send logs here, not needed 
            # if logs are coming from a container
            #- 12201:12201/udp
        networks: 
            - elk_net
        volumes:
            # Volume for logstash configuration
            - type: bind
              source: ./conf/logstash/logstash.conf
              target: /usr/share/logstash/pipeline/logstash.conf
            #- ./logs:/use/share/elasticsearch/data
        depends_on: 
            -  elasticsearch
    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.2
        container_name: kibana
        ports: 
            # Kibana interface
            - 5601:5601
        networks: 
            - elk_net
        volumes: 
            # Volume for kibana configuration
            - type: bind
              source: ./conf/kibana/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
        depends_on: 
            - logstash

networks: 
    elk_net:
        driver: bridge

